### ISSUE TITLE
Share function stops working after removing Work Profile from the system

### ISSUE THREAD

**Issue by resiehnnes** [LinkSheet/LinkSheet#473]
### Bug description

I've found a [bug ticket](https://github.com/LinkSheet/LinkSheet/issues/419) with pretty much same problem, but the thing is that if I remove created work profile from the system the share function stops working. Reinstalling LinkSheet does not solve the issue, and only way to make it work again is to create a new work profile and keep it if I want to use share functionality in LinkSheet.

The author of another bug report I mentioned above as it seems has the same device, so maybe this issue is only specific to Xiaomi devices. Let me know if you need any sort of debug logs, will gladly help you.

### Experiments

- [x] I have disabled all experiments

### Version

master-73c8102-dirty-nightly

### Device

Xiaomi 14 Ultra

### Android version

Android 14

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Thanks for the bug report, I have a few questions:

* How are you creating the work profile? (Does Xiaomi offer this in MIUI natively?)
* Which "share function" are you referring to?
* Do you have "Enable profile switching" in LinkSheet settings -> Advanced -> Feature flags enabled

**Comment by 1fexd** [comment]
Could you please share the log?

**Comment by resiehnnes** [comment]
@1fexd Here you go

[log.txt](https://github.com/user-attachments/files/17804757/log.txt)

**Comment by 1fexd** [comment]
Hm, there's no indication of any issue in the log file - are you familiar with Android logcat?

**Comment by resiehnnes** [comment]
@1fexd Yes, I can try to reproduce the steps needed (open link -> linksheet pops up -> try sharing link, remembering timestamps) while running logcat and share the output. Let me know if any other steps are necessary. I am not sure how sensitive .log information is, so if you don't mind I rather have your email to send log file.

**Comment by 1fexd** [comment]
Sure, please send it either via Discord (1fexd), Matrix (@1fexd:matrix.org) or directly via mail (1fexd _at_ 420blaze _dot_ it)

**Comment by resiehnnes** [comment]
@1fexd Done 👍

**Comment by 1fexd** [comment]
Thanks, would you mind checking if the latest nightly build fixes this issue?

**Comment by resiehnnes** [comment]
@1fexd Unfortunately latest nightly (77e2a11) has same problem on my device. I noticed that systems share overlay opens up in a different way now when pressing "Share link" button, like, it slides out from the left side.

I will test if this problem occurs on two other devices and come back shortly

**Comment by resiehnnes** [comment]
So, tried to reproduce this bug on two older devices (Insular -> Work profile -> LinkSheet Nightly) and both work as intended.

Huawei VOG-L29 (Android 10)
Samsung SM-G955F (Android 9)

**Comment by resiehnnes** [comment]
Tried latest nightly and "Share link" still doesn't work. I even tried to create a work profile and delete it afterwards to see if that could matter.

**Comment by 1fexd** [comment]
Does this also occur in other apps?

**Comment by resiehnnes** [comment]
Nope, every other app I use to share media works just fine.

**Comment by 1fexd** [comment]
Would you mind testing if the "Ignore LibRedirect" button works? (You'll have to enable LibRedirect from the Links settings page, then set it up for a service such as Youtube, then enable the Ignore LibRedirect button from the Bottom sheet settings page)

**Comment by resiehnnes** [comment]
Same as with "Share link", after pressing "Ignore LibRedirect" LinkSheet closes and nothing happens.

https://github.com/user-attachments/assets/0acdb726-7c3d-4d6f-9876-f22894dc1f94

**Comment by 1fexd** [comment]
Hm, kind of looks like it might be related to [this](https://stackoverflow.com/a/77329995)? Additionally, could you please check if there are any other Xiaomi specific settings related to "performance", background launched and/or battery optimizations?

**Comment by resiehnnes** [comment]
Oh wow, I had no idea something like this could be the reason.. So I gave permission "Display pop-up windows" as mentioned in the link you provided and "voila" it did the trick, "Share link" works now. Thank you for your time and sorry for this weird bug which was on Xiaomi's side as it turns out. LinkSheet was working fine (without "Display pop-up windows" permission) until I removed a Work Profile from the system.

One more thing to make sure it's not a bug, when I tap "Ignore LibRedirect" the LinkSheet popup just closes, shouldn't it reopen with "original" link afterwards, or am I missing something?

**Comment by 1fexd** [comment]
> Oh wow, I had no idea something like this could be the reason.. So I gave permission "Display pop-up windows" as mentioned in the link you provided and "voila" it did the trick, "Share link" works now. Thank you for your time and sorry for this weird bug which was on Xiaomi's side as it turns out. LinkSheet was working fine (without "Display pop-up windows" permission) until I removed a Work Profile from the system.

Glad to hear that - I'll add some info that shows up only on Xiaomi phones about this

> One more thing to make sure it's not a bug, when I tap "Ignore LibRedirect" the LinkSheet popup just closes, shouldn't it reopen with "original" link afterwards, or am I missing something?

Nope, not missing anything, this is in fact a bug (should be fixed now), thanks!

**Comment by resiehnnes** [comment]
> Nope, not missing anything, this is in fact a bug (should be fixed now), thanks!

Can confirm, works as intended now. Thank you, donated! 🍻

**Comment by 1fexd** [comment]
I've just pushed [1732915177](https://github.com/LinkSheet/nightly/releases/tag/1732915177) which adds a new option in `Settings` -> `Debug` called `Audit MIUI environment` which shows up on Xiaomi devices - is there any chance you could run it (just does some MIUI-specific probing so I can try to develop a solution/display an alert with a direct link to Xiaomi's special settings page), then send me the result it copies to the clipboard?

**Comment by resiehnnes** [comment]
Done. Check your mailbox.

**Comment by 1fexd** [comment]
The latest build should show an alert on the main page if LinkSheet does not have permission to display pop-up windows - could you please turn it off manually through system settings, then check if the alert shows up and if the button to grant it works?

**Comment by resiehnnes** [comment]
Looks like I mistakenly confused "Display pop-up windows" with "Open new windows while running" permission. Apparently "Open new windows while running" was the one needed for "Share link" button to function properly. I am sorry for that, hopefully it won't take much time to rework the code. So once again, granting "Display pop-up windows" permission does not solve non-working "Share link" function, but granting "Open new windows while running" does make it work.

Regarding alert, it is there and shows always despite "Display pop-up windows" permission status. Grant button doesn't do anything.

I recorded a video to show what's going on. It shows that "Open new windows while running" permission is needed to be able to use "Share link" button.  Also it shows that alert message stays there despite granted permissions.

https://github.com/user-attachments/assets/6e180629-3290-4661-af10-17f0e2d07b68

**Comment by 1fexd** [comment]
Just pushed a fix which targets the correct permission, building now - unfortunately, this one can't directly be requested so it attempts to redirect to the system settings instead

**Comment by resiehnnes** [comment]
I am pretty confused now, because after removing/installing multiple times different nightly builds from the last week it seems that "Open new windows while running" permission is granted by default. Is it possible that LinkSheet grants it upon install by default, or does this means the system retains that it was granted to specific app and restores it upon reinstall? 🤷‍♂️

For the sake of science I tried to install a good bunch of random apps from F-Droid and 10 out of 10 had this permission granted right after install. After that I went through the list of my apps which were installed for a long time now and most of them DO NOT have this permission granted. Hm.. next I tried to reinstall them and see if they retain "Deny" status for "Open new windows while running" permission and they indeed did.

Not sure what is happening here. I have to notice that my device is rooted, running stock ROM but has couple of mods and tweaks here and there, I don't know but maybe that is the cause of some unexplained bugs.. Would be nice if someone with similar device could check the status of "Open new windows while running" permission after clean LinkSheet install, because I am pretty positive that I did not changed anything there, but as it turned out both (LinkSheet 0.0.33 and LinkSheet Nightly) had this permission revoked which made "Share link" button non-functional if a Work Profile is removed from the system. Now I actually wonder if "Share link" + revoked "Open new windows while running" permission would work on a clean Xiaomi system where Work Profile was never created.... I would gladly test it when I will make factory reset, probably in couple of months when HyperOS 2 will land for Europe devices.

One last thing to mention that there is an app which is asking a user to go and grant "Open new windows while running" to function properly on Xiaomi devices, this app is called "[Scrambled Exif](https://gitlab.com/juanitobananas/scrambled-exif/tree/HEAD)" (see screenshot). if I reinstall it "Open new windows while running" is not granted by default, and this warning is shown every time upon app launch even after granting this needed permission, maybe that's why it has "Do not show again" option to hide this warning manually. I noticed that your latest build keeps showing this warning despite the status of "Open new windows while running" permission, I guess there is no way to make a check if it's granted or not.

<img src="https://github.com/user-attachments/assets/918bff4d-29e7-42d7-b575-4300dd52a1ca" width="300"/>

**Comment by resiehnnes** [comment]
> unfortunately, this one can't directly be requested so it attempts to redirect to the system settings instead

Works good and pretty straightforward.

https://github.com/user-attachments/assets/1cd40396-1b70-4693-8a9b-b2a17ffdb889

**Comment by 1fexd** [comment]
> I am pretty confused now, because after removing/installing multiple times different nightly builds from the last week it seems that "Open new windows while running" permission is granted by default. Is it possible that LinkSheet grants it upon install by default, or does this means the system retains that it was granted to specific app and restores it upon reinstall? 🤷‍♂️
> 
> For the sake of science I tried to install a good bunch of random apps from F-Droid and 10 out of 10 had this permission granted right after install. After that I went through the list of my apps which were installed for a long time now and most of them DO NOT have this permission granted. Hm.. next I tried to reinstall them and see if they retain "Deny" status for "Open new windows while running" permission and they indeed did.
> 
> Not sure what is happening here. I have to notice that my device is rooted, running stock ROM but has couple of mods and tweaks here and there, I don't know but maybe that is the cause of some unexplained bugs.. Would be nice if someone with similar device could check the status of "Open new windows while running" permission after clean LinkSheet install, because I am pretty positive that I did not changed anything there, but as it turned out both (LinkSheet 0.0.33 and LinkSheet Nightly) had this permission revoked which made "Share link" button non-functional if a Work Profile is removed from the system. Now I actually wonder if "Share link" + revoked "Open new windows while running" permission would work on a clean Xiaomi system where Work Profile was never created.... I would gladly test it when I will make factory reset, probably in couple of months when HyperOS 2 will land for Europe devices.
> 
> One last thing to mention that there is an app which is asking a user to go and grant "Open new windows while running" to function properly on Xiaomi devices, this app is called "[Scrambled Exif](https://gitlab.com/juanitobananas/scrambled-exif/tree/HEAD)" (see screenshot). if I reinstall it "Open new windows while running" is not granted by default, and this warning is shown every time upon app launch even after granting this needed permission, maybe that's why it has "Do not show again" option to hide this warning manually. I noticed that your latest build keeps showing this warning despite the status of "Open new windows while running" permission, I guess there is no way to make a check if it's granted or not.
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/52158526/391350559-918bff4d-29e7-42d7-b575-4300dd52a1ca.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTkxMDUsIm5iZiI6MTczMzExODgwNSwicGF0aCI6Ii81MjE1ODUyNi8zOTEzNTA1NTktOTE4YmZmNGQtMjllNy00MmQ3LWI1NzUtNDMwMGRkNTJhMWNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA1NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZWY2YzM3NjdjOGYzZWJjNDNmNTlhNjEyZTNlNTI0NTFiMjY2YzFiMTFiMWY0MjFmNDUxOGFjNGFhNDAyZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t8VVOFk4HYGQrsiQDY8DOQDO2WmBVaZTVc-LhUU9Lnc">

Thanks for your investigation, appreciate it!

**Comment by 1fexd** [comment]
> > unfortunately, this one can't directly be requested so it attempts to redirect to the system settings instead
> 
> Works good and pretty straightforward.
> linksheet_other2.mp4

Fantastic, does the alert disappear automatically? In the video it doesn't for some reason

**Comment by resiehnnes** [comment]
> Fantastic, does the alert disappear automatically? In the video it doesn't for some reason

Nope, it stays there after granting permission.

**Comment by 1fexd** [comment]
I've just pushed a small change to the MIUI auditing functionality, would it be possible for you to run it twice, once with "Open new windows while running in background" enabled and once without, and then share both results?

**Comment by resiehnnes** [comment]
Hm, just tried and nothing really changed, the alert doesn't disappear when I allow "Open new windows while running in background". Couldn't be the reason why author of "[Scrambled Exif](https://gitlab.com/juanitobananas/scrambled-exif/tree/HEAD)" has "Don't show again" button when alert pop's up?

**Comment by 1fexd** [comment]
> Couldn't be the reason why author of "[Scrambled Exif](https://gitlab.com/juanitobananas/scrambled-exif/tree/HEAD)" has "Don't show again" button when alert pop's up?

It might be, yes, however to be absolutely sure I updated the auditing feature so I can check if I'm checking for the correct permission in the alert

**Comment by 1fexd** [comment]
Just pushed a fix

**Comment by resiehnnes** [comment]
Here you go:

```
{
  "10000": -1,
  "10001": 0,
  "10002": 0,
  "10003": 0,
  "10004": 0,
  "10005": 0,
  "10006": 0,
  "10007": 0,
  "10008": 1,
  "10009": 0,
  "10010": 0,
  "10011": 0,
  "10012": 0,
  "10013": 0,
  "10014": 0,
  "10015": 0,
  "10016": 0,
  "10017": 5,
  "10018": 0,
  "10019": 1,
  "10020": 0,
  "10021": 0,
  "10022": 0,
  "10023": 0,
  "10024": 0,
  "10025": 0,
  "10026": 0,
  "10027": 0,
  "10028": 0,
  "10029": 0,
  "10030": 0,
  "10031": 0,
  "10032": 0,
  "10033": 0,
  "10034": 0,
  "10035": 0,
  "10036": 0,
  "10037": 0,
  "10038": 0,
  "10039": 0,
  "10040": 0
}
```

**Comment by 1fexd** [comment]
Alright, I think I got the correct one now :D

**Comment by resiehnnes** [comment]
Yes, works as intended now, alert hides when permission is granted, and comes back when revoked 👍 I would make a small text correction in alert in the second paragraph to make it more distinct which permission has to be allowed:

"Tap the button below and allow "Open new windows while in background" permission"

**Comment by 1fexd** [comment]
Great - thanks for your help with debugging and solving this issue
